//to be autogenerated as template, one per resource
import { Entity, Column, PrimaryGeneratedColumn } from "typeorm";

@Entity("Albums")
export class AlbumsEntity {
  @PrimaryGeneratedColumn()
  id: number;

  @Column({nullable: true})
Albumname: string;

@Column({nullable: true})
Numberoftracks: string;

@Column({nullable: true})
Totalduration: string;

@Column({nullable: true})
Id: string;


}
