//to be autogenerated as template, one per resource
import { Entity, Column, PrimaryGeneratedColumn } from "typeorm";

@Entity("Artists")
export class ArtistsEntity {
  @PrimaryGeneratedColumn()
  id: number;

  @Column({nullable: true})
Artistname: string;

@Column({nullable: true})
Dateofbirth: string;

@Column({nullable: true})
Gender: string;

@Column({nullable: true})
Band: string;

@Column({nullable: true})
Id: string;


}
