//to be autogenerated as template, one per resource
import { Entity, Column, PrimaryGeneratedColumn } from "typeorm";

@Entity("Tracks")
export class TracksEntity {
  @PrimaryGeneratedColumn()
  id: number;

  @Column({nullable: true})
Name: string;

@Column({nullable: true})
Duration: string;

@Column({nullable: true})
Album: string;

@Column({nullable: true})
Genre: string;

@Column({nullable: true})
Id: string;


}
